import * as fs from 'fs';
import * as path from 'path';
import { ComparisonResult, VendorWithCriteria, ChartDataPoint } from '../types';
import {
  criteriaRadarData,
  marketPositionDistribution,
  getRankingCriteriaMetadataForCategory,
} from '../analysis/ranking';
import { asciiBarChart } from '../analysis/comparator';

// ─── ASCII Terminal Charts ───────────────────────────────────────────────────

/**
 * Prints an ASCII bar chart to console for a category's rankings.
 */
export function printAsciiRanking(result: ComparisonResult): void {
  console.log(`\n  Vendor Rankings — ${result.categoryName}`);
  console.log('  ' + '─'.repeat(70));
  if (result.scoreDistribution.length === 0) {
    console.log('  (no vendors)');
    return;
  }
  const chart = asciiBarChart(result.scoreDistribution, 40);
  chart.split('\n').forEach(line => console.log('  ' + line));
  console.log('  ' + '─'.repeat(70));
  console.log(`  Average: ${result.averageScore}/10 | Top: ${result.topVendor}`);
  console.log();
}

// ─── HTML Chart Generator ─────────────────────────────────────────────────────

/**
 * Generates a self-contained HTML file with Chart.js visualisations
 * for all categories (bar charts + pie charts + radar for top vendor).
 */
export function generateHtmlCharts(
  results: ComparisonResult[],
  outputPath: string,
): void {
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const chartSections = results.map(r => buildCategoryChartSection(r)).join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vendors AI Master — Dashboard</title>
  <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; background: #0f172a; color: #e2e8f0; padding: 2rem; }
    h1  { font-size: 1.8rem; margin-bottom: 0.5rem; color: #38bdf8; }
    h2  { font-size: 1.3rem; margin: 2rem 0 1rem; color: #7dd3fc; border-bottom: 1px solid #1e3a5f; padding-bottom: 0.4rem; }
    h3  { font-size: 1.05rem; margin: 1.5rem 0 0.5rem; color: #94a3b8; }
    .subtitle { color: #64748b; font-size: 0.85rem; margin-bottom: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(520px, 1fr)); gap: 1.5rem; margin-bottom: 1rem; }
    .card { background: #1e293b; border: 1px solid #1e3a5f; border-radius: 12px; padding: 1.25rem; }
    .chart-wrapper { position: relative; height: 300px; }
    .stat-row { display: flex; gap: 1.5rem; flex-wrap: wrap; margin-bottom: 1rem; }
    .stat { background: #0f172a; border-radius: 8px; padding: 0.6rem 1rem; font-size: 0.8rem; }
    .stat span { display: block; font-size: 1.1rem; font-weight: 600; color: #38bdf8; }
    footer { margin-top: 3rem; text-align: center; font-size: 0.75rem; color: #475569; }
  </style>
</head>
<body>
  <h1>Vendors AI Master — Dashboard</h1>
  <p class="subtitle">Generated: ${new Date().toLocaleString()} | AI &amp; Cybersecurity Vendor Analysis</p>

  ${chartSections}

  <footer>Generated by Vendors AI Master &bull; LM Studio (Gemma-3-4b) &bull; ReAct Agent</footer>

  <script>
    Chart.defaults.color = '#94a3b8';
    Chart.defaults.borderColor = '#1e3a5f';
  </script>
</body>
</html>`;

  fs.writeFileSync(outputPath, html, 'utf-8');
}

// ─── Internal Helpers ─────────────────────────────────────────────────────────

function buildCategoryChartSection(result: ComparisonResult): string {
  if (result.vendors.length === 0) return '';

  const catId = result.categoryName.replace(/[^a-zA-Z0-9]/g, '_');
  const barData = buildBarChartData(result.scoreDistribution);
  const pieData = buildPieChartData(marketPositionDistribution(result.vendors));
  const criteriaComparisonData = buildCriteriaComparisonChartData(result.vendors);

  // Top vendor radar
  const topVendor = result.vendors[0];
  const radarData = topVendor ? buildRadarChartData(criteriaRadarData(topVendor), topVendor.name) : '';

  return `
  <h2>${escHtml(result.categoryName)}</h2>
  <div class="stat-row">
    <div class="stat">Vendors Analysed <span>${result.vendors.length}</span></div>
    <div class="stat">Top Vendor <span>${escHtml(result.topVendor)}</span></div>
    <div class="stat">Average Score <span>${result.averageScore}/10</span></div>
  </div>
  <div class="grid">
    <div class="card">
      <h3>Score Ranking</h3>
      <div class="chart-wrapper"><canvas id="bar_${catId}"></canvas></div>
    </div>
    <div class="card">
      <h3>Market Position Distribution</h3>
      <div class="chart-wrapper"><canvas id="pie_${catId}"></canvas></div>
    </div>
    <div class="card">
      <h3>Criteria Comparison by Vendor</h3>
      <div class="chart-wrapper"><canvas id="criteria_${catId}"></canvas></div>
    </div>
    ${topVendor ? `
    <div class="card">
      <h3>Top Vendor Criteria — ${escHtml(topVendor.name)}</h3>
      <div class="chart-wrapper"><canvas id="radar_${catId}"></canvas></div>
    </div>` : ''}
  </div>

  <script>
  (function() {
    // Bar chart
    new Chart(document.getElementById('bar_${catId}'), {
      type: 'bar',
      data: ${barData},
      options: {
        indexAxis: 'y',
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { display: false } },
        scales: {
          x: { min: 0, max: 10, ticks: { stepSize: 1 } }
        }
      }
    });

    // Pie chart
    new Chart(document.getElementById('pie_${catId}'), {
      type: 'doughnut',
      data: ${pieData},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: { legend: { position: 'right' } }
      }
    });

    // Criteria comparison chart
    new Chart(document.getElementById('criteria_${catId}'), {
      type: 'bar',
      data: ${criteriaComparisonData},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        plugins: {
          legend: { position: 'bottom' },
        },
        scales: {
          y: { min: 0, max: 10, ticks: { stepSize: 1 } },
        },
      }
    });

    ${topVendor && radarData ? `
    // Radar chart
    new Chart(document.getElementById('radar_${catId}'), {
      type: 'radar',
      data: ${radarData},
      options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: { r: { min: 0, max: 10, ticks: { stepSize: 2 } } }
      }
    });` : ''}
  })();
  </script>`;
}

const CHART_COLORS = [
  '#38bdf8', '#818cf8', '#34d399', '#fb923c', '#f472b6',
  '#a78bfa', '#4ade80', '#facc15', '#60a5fa', '#f87171',
];

function buildBarChartData(data: ChartDataPoint[]): string {
  return JSON.stringify({
    labels: data.map(d => d.label),
    datasets: [{
      label: 'Score',
      data: data.map(d => d.value),
      backgroundColor: data.map((d, i) => d.color ?? CHART_COLORS[i % CHART_COLORS.length]),
      borderRadius: 4,
    }],
  });
}

function buildPieChartData(data: ChartDataPoint[]): string {
  return JSON.stringify({
    labels: data.map(d => d.label),
    datasets: [{
      data: data.map(d => d.value),
      backgroundColor: CHART_COLORS.slice(0, data.length),
    }],
  });
}

function buildRadarChartData(data: ChartDataPoint[], vendorName: string): string {
  return JSON.stringify({
    labels: data.map(d => d.label),
    datasets: [{
      label: vendorName,
      data: data.map(d => d.value),
      fill: true,
      backgroundColor: 'rgba(56, 189, 248, 0.15)',
      borderColor: '#38bdf8',
      pointBackgroundColor: '#38bdf8',
    }],
  });
}

function buildCriteriaComparisonChartData(vendors: VendorWithCriteria[]): string {
  const ranked = [...vendors].sort((a, b) => b.rankingScore - a.rankingScore);
  const labels = ranked.map(v => v.name);
  const metadata = getRankingCriteriaMetadataForCategory(ranked[0]?.categoryName);

  const datasets = metadata.map((criterion, i) => ({
    label: criterion.label,
    data: ranked.map(v => (v.criteria ? (v.criteria as any)[criterion.key] ?? 0 : 0)),
    backgroundColor: CHART_COLORS[i % CHART_COLORS.length],
    borderRadius: 3,
  }));

  return JSON.stringify({ labels, datasets });
}

function escHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
